version: '3.9'

services:
  de-pg-cr-af:
    image: sindb/de-pg-cr-af:latest
    ports:
      - 3000:3000
      - 3002:3002
      - 15432:5432
    volumes:
      - s5t4postgresql:/var/lib/postgresql
      - ${AIRFLOW_DAGS_DIR:-./dags}:/lessons/dags

  metabase:
    image: metabase/metabase
    ports:
      - 3333:3000

volumes:
  s5t4postgresql:
